### ISSUE TITLE
Downloading Images

### ISSUE THREAD

**Issue by Invisible40** [PactInteractive/image-downloader#6] opened 2015-02-16 19:16 UTC
For some reason, now I can't download any images off of the Image Downloader. For example, I try it on a Tumblr page, with multiple images of it. They appear in the extension's box, however when I select them all and click Download it will not download (loads in green saying Downloading # photos) then disappears when in reality nothing happened.

It previously worked the same way I was trying, but again now it does not work. Even trying to download one image doesn't work.

And nothing shows in my Downloads page for Chrome.

**Comment by Selezon** [comment] 2016-06-06 10:46
The app has changed for the worse.
The window that displays the image while maintaining the site closes each picture. Now, to save the next picture you need to run an application every time anew. It is not easy and takes a lot of time.

**Comment by vdsabev** [comment] 2016-06-06 11:20
Hey, @Selezon, thanks for taking the time to provide feedback!

The extension actually hasn't changed in about 2 years, what's probably changed is the Google Chrome browser. I was unable to reproduce the issue you described - downloads works for me on Windows 10, Google Chrome 51.0.2704.79 m, the same way they have for the past few years.

I develop and maintain this extension in my free time, which isn't a lot these days. It would be very helpful if you could assist me in reproducing the issue you described, by providing the URL of the website where you've experienced it, your operating system, as well as your Google Chrome browser version.

But even so, I might be unable to fix the issue due to having a full-time day job, as I'm sure most of us here do. So pull requests are very much appreciated :bow:

Thanks again!

**Comment by KCampo81** [comment] 2020-06-21 20:19
Why does it only allow you to download some of the photos at a time and not all the photos on the page?

**Comment by vdsabev** [comment] 2021-04-25 22:54
Closing this issue as it hasn't had activity in a while. If the issue persists, please leave a comment or open a new issue. Thanks!

**Closed by vdsabev** 2021-04-25 22:54 UTC
